version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
