services:
  spare-queen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - uploads_data:/usr/src/app/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  uploads_data:
    driver: local